### PR TITLE
Debian packaging upgraded / configured for git-buildpackage

### PR DESCRIPTION
**Pull request by Ichthyostega**
Hello @valgit 
as discussed in https://github.com/slowmoVideo/slowmoVideo/issues/46, I've now done an upgrade and slight rework of the debian packaging for slowmoVideo. This new package builds for me on Debian/Jessy (Stable), Ubuntu/Trusty, Vivid, Wily and Xenial.<br/>
See my [ppa:ichthyo/video](https://launchpad.net/~ichthyo/+archive/ubuntu/video)

With this change, I'd propose to use a setup and git repository layout suitable for the tool **`git-buildpackage`**. [->documentation](http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.html). This setup is fully compatible with standard debian package layout, and in fact used by many debian package maintainers. The key point is, that with this setup, you're able to generate a full DEB package just from the Git-Repo, with a single command. No fussing around with "upstream tarballs" anymore. But if you want, you can also use the standard way to build a package from the same tree.

The basic idea is to have the debian packaging on a separate branch in git. Typically this branch is labelled `debian`. Please note, this branch is _not meant to be merged_ to master. The whole Idea is to keep `master` clean and free of any debian related artefacts. Thus, the tooling is able just to pull the "upstram tarball" from the tagged master, and then add the debian packaging from the corresponding tag on the `debian` tree. To this end, I'll send you also another pull request against slowmoVideo/master, just to remove the (stale) debian/ folder from there.

While I looked thrugh the packaging, I've also done some upgrades and polishing, based on current packaging standard. Hope this was OK for you.

Of course I do not want to force anything onto you. Please see this just as a recommendation, I'll build a lot of debian packages for various reasons, and I value this setup due to its clarity and convenience.

And btw, thanks for your work on slowmoVideo, great stuff!

### CODE REVIEW

**Comment by Ichthyostega** [comment]
just to be clear: the idea is to have a separate 'debian' branch, **not** to merge this back to master.. ;-)

**Comment by Ichthyostega** [comment]
Hello @valgit 
as discussed in the other pull request #82 , I've fixed the superfluous Qt4 and libsdl dependency and rebuilt all packages

Regarding the proposal to build on Trusty with Qt4, I've tried that out, but it doesn't work. Configuring works and picks up Qt4, but compilation fails with

    /PKGBUILDDIR/src/slowmoVideo/slowmoUI/frameMonitor.h:39:49: error:
    Q_DECL_OVERRIDE  does not name a type
    virtual void closeEvent(QCloseEvent *event) Q_DECL_OVERRIDE;`

compilation with Qt5 works of course

**Comment by valgit** [comment]
hello @Ichthyostega , the error came by the fact that Q_DECL_OVERRIDE is only defined on QT5 ;-) it can be remove without problem (only compiler hint), i will look at that.

**Comment by pmo-19** [comment]
@Ichthyostega How come you are `unable to build with Qt4` ? I have never encountered problem building with Qt4 (of course without modifying the source code) ... May be you are lacking some required `CMake skills` ? and as well debian folder building skills. I can give you a hint: the solution is not in patching the source but rather in understanding what the debian folder do and of course having a basic unserstanding of `CMake`.
So @valgit you don't need to mess with the source code because you chosen partner is unable to live up to his own promises ...
How about finding a `CMake Bible` somewhere ? to be able to lecture peoples here ...
@Ichthyostega You see you are the reason why I will not release my debian folders. I believe you are just acting as if you are in the know of everything but facing reality you seem to be far less achieving than your polished fuss rhetoric ... :-)
I will publish in my own PPA rather soon I believe, but right before I will issue a `copyright notice` within the `debian/copyright file` forbidding you `Mr. Hermann Foßeler` from using the modification I did within the debian folder, in order to build at will for Qt4 / Qt5, to use 4 processor cores to build, and to use `GCC Options -O3` instead of `-O2`.
That would will be in place to avoid that the `imposter` that you are in the real world could at will use the work of another one person you already copiously insulted before.

**Comment by valgit** [comment]
I have merge this PR in branch  `debian`. there is a need to update the wiki.

**Comment by Ichthyostega** [comment]
@valgit I will look into the wiki / documentation once I'm back home tomorrow

**Pull request closed without merging**
